version: "3"

services:
    app:
        build: 
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manange.py runserver 0.0.0.0:8000"